transmission:
  command: transmission
  uid: 0
  gid: 0
  url: http://localhost:9091
  username: client
  password: client
pia:
  user: p1786392
  password: lu6wyd8ugS6oaW5oj8iD
openvpn:
  command: openvpn
